#!/bin/bash

set -e # Exit with nonzero exit code if anything fails

echo "Defining the function to compress the site"
function doCompress {
    echo "Compressing the site"
    npm run gulp
}

# Run our compress script
doCompress
